lint:
  rules:
    remove:
      - REPEATED_FIELD_NAMES_PLURALIZED
      - ENUM_FIELD_NAMES_PREFIX
      - ENUM_FIELD_NAMES_ZERO_VALUE_END_WITH
  rules_option:
    max_line_length:
      max_chars: 120
    indent:
      style: 4
      newline: "\n"
