name: CI back
on:
  push:
    paths:
      - "build.sbt"
      - "./project/**"
      - "./src/**"
  pull_request:
    paths:
      - "build.sbt"
      - "./project/**"
      - "./src/**"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 8
      - name: Install dependencies
        run: npm install
      - name: Build
        run: sbt +compile
