name: CI
on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2.4.1
        with:
          node-version: 16
      - name: Install dependencies
        run: npm install
        working-directory: ./ui
      - name: Build
        run: npm run build
        working-directory: ./ui
